"use strict";(self.webpackChunkdocs=self.webpackChunkdocs||[]).push([[351],{74894:function(e,t,n){n.r(t),n.d(t,{frontMatter:function(){return s},contentTitle:function(){return l},metadata:function(){return h},toc:function(){return c},default:function(){return d}});var a=n(87462),o=n(63366),i=(n(67294),n(3905)),r=["components"],s={sidebar_position:4},l="Why use Promises?",h={unversionedId:"WhyUsePromises",id:"WhyUsePromises",isDocsHomePage:!1,title:"Why use Promises?",description:"Before diving in to Promises themselves, you might need some convincing of why we should even use Promises to begin with. That's totally fair! The following text should give you a brief introduction to Promises and a good understanding of why they are useful.",source:"@site/docs/WhyUsePromises.md",sourceDirName:".",slug:"/WhyUsePromises",permalink:"/roblox-lua-promise/docs/WhyUsePromises",editUrl:"https://github.com/evaera/roblox-lua-promise/edit/master/docs/WhyUsePromises.md",tags:[],version:"current",sidebarPosition:4,frontMatter:{sidebar_position:4},sidebar:"defaultSidebar",previous:{title:"Tour of Promises",permalink:"/roblox-lua-promise/docs/Tour"},next:{title:"Examples",permalink:"/roblox-lua-promise/docs/Examples"}},c=[{value:"Threads",id:"threads",children:[]},{value:"Coroutines",id:"coroutines",children:[]},{value:"Problems with the Coroutine Model",id:"problems-with-the-coroutine-model",children:[]},{value:"Enter Promises",id:"enter-promises",children:[]},{value:"Composing Promises",id:"composing-promises",children:[]},{value:"Wait, nevermind.",id:"wait-nevermind",children:[]},{value:"Propagation",id:"propagation",children:[]},{value:"But I want to be able to use pre-existing functions that yield!",id:"but-i-want-to-be-able-to-use-pre-existing-functions-that-yield",children:[]},{value:"Problems, revisited",id:"problems-revisited",children:[]},{value:"Next steps",id:"next-steps",children:[]}],u={toc:c};function d(e){var t=e.components,n=(0,o.Z)(e,r);return(0,i.kt)("wrapper",(0,a.Z)({},u,n,{components:t,mdxType:"MDXLayout"}),(0,i.kt)("h1",{id:"why-use-promises"},"Why use Promises?"),(0,i.kt)("p",null,"Before diving in to Promises themselves, you might need some convincing of why we should even use Promises to begin with. That's totally fair! The following text should give you a brief introduction to Promises and a good understanding of why they are useful."),(0,i.kt)("h2",{id:"threads"},"Threads"),(0,i.kt)("p",null,'When writing programs, it\'s possible to divide functions into two groups: "synchronous" and "asynchronous". A "synchronous operation" is one that can run to completion and generate any necessary return values with only the information available to your code at the time the operation begins. For example, a function that takes two Parts and returns the distance between them would be synchronous, because all information needed to compute that value is available when you call the function.'),(0,i.kt)("p",null,"But sometimes situations arise where we call a function that needs access to a value that ",(0,i.kt)("em",{parentName:"p"},"doesn't"),' exist at call time. This could be because it requires a network request to get the data, or the user needs to input some text, or we\'re waiting for another process to finish computation and give us the value. In any case, we refer to this as an "asynchronous operation".'),(0,i.kt)("p",null,"The simplest way to deal with this is to just stop execution of the thread, or \"block\". This means that when you call a function that needs some data that doesn't exist yet, the entire thread stops running and waits for the data to be ready before returning and continuing. This is actually how many low-level languages typically model asynchronous operations. To allow tasks to run at the same time, programs will create new threads that branch from parent threads and jump back on when they're finished blocking. However, this presents challenges with sharing memory and synchronizing data across threads, because at the operating system level threads truly are running in parallel."),(0,i.kt)("h2",{id:"coroutines"},"Coroutines"),(0,i.kt)("p",null,"To simplify sharing memory and potentially reduce overhead, many programs will emulate a multi-threaded environment using green threads or coroutines, which are run concurrently inside of one OS thread. The key difference between OS threads and coroutines is that coroutines do not ",(0,i.kt)("em",{parentName:"p"},"actually"),' run in parallel -- only one coroutine is ever executing at a time. In the context of Lua, the term "thread" is used to refer to a coroutine, but they are not the same thing as OS threads.'),(0,i.kt)("p",null,"To facilitate this emulation, a thread scheduler is introduced to keep track of the emulated threads and decide which thread to run next when the current thread yields. Yielding is similar to blocking, except when a coroutine yields, it signals to the thread scheduler that it can run other code and resume the thread at a later time."),(0,i.kt)("p",null,"When the game starts, each Script and LocalScript in your game becomes its own Lua thread in the thread scheduler and each script is run either to completion or until it yields. Once all of the scripts have gone through this process, Roblox does other things like updating humanoids and running physics. After all that's done, the next frame begins and this process repeats until the game closes."),(0,i.kt)("p",null,"So, what really happens when we call an asynchronous function like ",(0,i.kt)("inlineCode",{parentName:"p"},"Player:IsInGroup"),"? Well, the current Lua thread yields (letting other Lua code start running elsewhere in your game), and Roblox makes a new OS thread which blocks on an HTTP request to their internal group APIs in the background. Sometime in the future when that request comes back, the value jumps back onto the main Roblox thread and your Lua thread is scheduled to be resumed with the given arguments on the next step."),(0,i.kt)("h2",{id:"problems-with-the-coroutine-model"},"Problems with the Coroutine Model"),(0,i.kt)("p",null,"Coroutines fix the memory sharing problem of OS threads, but they still inherit other problems when used on their own:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},"It's impossible to know if a function that you call is going to yield or not unless you look at the documentation or strictly abide by a naming convention (which is not realistic). Unintentionally yielding the thread is the source of a large class of bugs and race conditions that Roblox developers run into."),(0,i.kt)("li",{parentName:"ul"},"When an asynchronous operation fails or an error is encountered, Lua functions usually either raise an error or return a success value followed by the actual value. Both of these methods lead to repeating the same tired patterns many times over for checking if the operation was successful, and make composing multiple asynchronous operations difficult."),(0,i.kt)("li",{parentName:"ul"},"It is difficult to deal with running multiple asynchronous operations concurrently and then retrieve all of their values at the end without extraneous machinery."),(0,i.kt)("li",{parentName:"ul"},"Coroutines lack easy access to introspection without manual work to enable it at the call site."),(0,i.kt)("li",{parentName:"ul"},"Coroutines lack the ability to cancel an operation if the value is no longer needed without extraneous manual work at both the call site and the function implementation.")),(0,i.kt)("h2",{id:"enter-promises"},"Enter Promises"),(0,i.kt)("p",null,"In Lua, Promises are an abstraction over coroutines. A \"Promise\" is just an object which we can use to represent a value that exists in the future, but doesn't right now. Promises are first-class citizens in other languages like JavaScript, which doesn't have coroutines and facilitates all asynchronous code through callbacks alone."),(0,i.kt)("p",null,"When calling an asynchronous function, instead of yielding, the function returns a Promise synchronously. The Promise object allows you to then attach a callback function which will be run later when the Promise ",(0,i.kt)("em",{parentName:"p"},"resolves"),". The function you called is in charge of resolving the Promise with your value when it is done working."),(0,i.kt)("p",null,"Promises also have built-in error handling. In addition to resolving, a Promise can ",(0,i.kt)("em",{parentName:"p"},"reject"),", which means that something went wrong when getting the future value we asked for. You can attach a different callback to be run when the Promise rejects so you can handle any error cases."),(0,i.kt)("p",null,"Let's take a look at this in action. We will make a function which wraps ",(0,i.kt)("inlineCode",{parentName:"p"},"HttpService:GetAsync")," and instead of yielding, it will return a Promise."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-lua"},'local HttpService = game:GetService("HttpService")\nlocal function httpGet(url)\n    return Promise.new(function(resolve, reject)\n        local ok, result = pcall(HttpService.GetAsync, HttpService, url)\n\n        if ok then\n            resolve(result)\n        else\n            reject(result)\n        end\n    end)\nend\n')),(0,i.kt)("p",null,"Let's break this down. The ",(0,i.kt)("inlineCode",{parentName:"p"},"Promise.new")," function accepts a function, called an ",(0,i.kt)("em",{parentName:"p"},"executor"),", which receives a ",(0,i.kt)("inlineCode",{parentName:"p"},"resolve")," function and a ",(0,i.kt)("inlineCode",{parentName:"p"},"reject")," function. ",(0,i.kt)("inlineCode",{parentName:"p"},"Promise.new")," calls the executor on the next Lua step. ",(0,i.kt)("strong",{parentName:"p"},"Inside it, we have created a safe space to safely call yielding functions, which has no possibility of unintentionally delaying other parts of your code"),". Since the Promise value itself was already returned from the ",(0,i.kt)("inlineCode",{parentName:"p"},"httpGet")," function, we aren't delaying the return by yielding with ",(0,i.kt)("inlineCode",{parentName:"p"},"GetAsync"),"."),(0,i.kt)("p",null,"Let's use the value now:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-lua"},'local promise = httpGet("https://google.com")\n\npromise:andThen(function(body)\n    print("Here\'s the Google homepage:", body)\nend)\n\npromise:catch(function(err)\n    warn("We failed to get the Google homepage!", err)\nend)\n')),(0,i.kt)("p",null,"So, we call the ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," method on the Promise returned from ",(0,i.kt)("inlineCode",{parentName:"p"},"httpGet"),". If the Promise resolved, the handler we passed into ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," is called and given the resolved values as parameters (",(0,i.kt)("inlineCode",{parentName:"p"},"body")," in this example). "),(0,i.kt)("p",null,"Likewise, we attach a failure handler with ",(0,i.kt)("inlineCode",{parentName:"p"},"catch")," to be run if the Promise rejects."),(0,i.kt)("p",null,"But wait! In addition to attaching a callback, ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," and ",(0,i.kt)("inlineCode",{parentName:"p"},"catch")," also return ",(0,i.kt)("em",{parentName:"p"},"new")," Promises themselves! If the original Promise rejects, then the Promise returned from ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," will ",(0,i.kt)("em",{parentName:"p"},"also")," reject with the same error, allowing is to rewrite our code like this:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-lua"},'httpGet("https://google.com")\n    :andThen(function(body)\n        print("Here\'s the Google homepage:", body)\n    end)\n    :catch(function(err)\n        warn("We failed to get the Google homepage!", err)\n    end)\n')),(0,i.kt)("p",null,"The Promise returned from ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," will resolve with whatever value you return from the callback. "),(0,i.kt)("p",null,"And if that value returned from the ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," handler is itself a Promise, it is automatically chained onto and the Promise returned from ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," won't resolve until ",(0,i.kt)("em",{parentName:"p"},"that")," Promise resolves."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-lua"},'httpGet("https://google.com")\n    :andThen(function(body) -- not doing anything with body for this example\n        return httpGet("https://eryn.io") -- returning a new Promise here!\n    end)\n    :andThen(function(body) -- Doesn\'t get called until the above Promise resolves!\n        print("Here\'s the eryn.io homepage:", body)\n    end)\n    :catch(warn) -- Still catches errors from both Promises!\n')),(0,i.kt)("h2",{id:"composing-promises"},"Composing Promises"),(0,i.kt)("p",null,"Promises are ",(0,i.kt)("em",{parentName:"p"},"composable"),". This means that Promises can easily be used, interact with, and consume one another without manually threading values between them. We already saw above how returning a Promise from the ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," handler will chain onto it. Let's expand that idea by diving into some more ways you can compose Promises with each other:"),(0,i.kt)("p",null,"Let's assume that we have a number of asynchronous functions which all return Promises, ",(0,i.kt)("inlineCode",{parentName:"p"},"async1"),", ",(0,i.kt)("inlineCode",{parentName:"p"},"async2"),", ",(0,i.kt)("inlineCode",{parentName:"p"},"async3"),", ",(0,i.kt)("inlineCode",{parentName:"p"},"async3"),", etc. Calling one of these functions will return a Promise. But what if we want to call all of them in sequence, each one after the one before it finishes? It's as simple as this:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-lua"},'async1()\n    :andThen(async2)\n    :andThen(async3)\n    :andThen(async4)\n    :andThen(async5)\n    :catch(function(err)\n        warn("Oh no! This went wrong somewhere along the line:", err)\n    end)\n')),(0,i.kt)("p",null,"In this sample, we first call ",(0,i.kt)("inlineCode",{parentName:"p"},"async1"),", then we chain the rest of the functions together with ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen"),". If ",(0,i.kt)("em",{parentName:"p"},"any")," of the Promises returned from these functions ",(0,i.kt)("em",{parentName:"p"},"reject"),", then all remaining ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen"),"'d functions are skipped and it will jump instantly to the ",(0,i.kt)("inlineCode",{parentName:"p"},"catch")," handler. "),(0,i.kt)("p",null,"And as a side note, if you forget to add a ",(0,i.kt)("inlineCode",{parentName:"p"},"catch")," to a long chain of Promises and one of them errors, the Promise library is smart enough to emit a warning in the console. Always catch your Promises!"),(0,i.kt)("p",null,"Let's think of another situation. What if we want to run all of the functions concurrently, and wait for all of them to be done? We don't want to run them one after another, because sometimes that can be wasteful. We want them all to run at once! We can do this with the static method ",(0,i.kt)("inlineCode",{parentName:"p"},"Promise.all"),":"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-lua"},'Promise.all({\n    async1(),\n    async2(),\n    async3(),\n    async4()\n}):andThen(function(arrayOfResolvedValues)\n    print("Done running all 4 functions!")\nend):catch(function(err)\n    warn("Uh oh, one of the Promises rejected! Abort mission!")\nend)\n')),(0,i.kt)("p",null,(0,i.kt)("inlineCode",{parentName:"p"},"Promise.all")," accepts an array of Promise objects, and returns a new Promise. The new Promise will ",(0,i.kt)("em",{parentName:"p"},"resolve")," with an array of resolved values in the same places as the Promises were in the array. The new Promise will ",(0,i.kt)("em",{parentName:"p"},"reject")," if ",(0,i.kt)("em",{parentName:"p"},"any")," of the Promises that were passed in rejects."),(0,i.kt)("p",null,(0,i.kt)("a",{parentName:"p",href:"https://eryn.io/roblox-lua-promise/lib/#race"},(0,i.kt)("inlineCode",{parentName:"a"},"Promise.race"))," is similar to ",(0,i.kt)("inlineCode",{parentName:"p"},"Promise.all"),", except it will resolve or reject as soon as one of the Promises resolves or rejects."),(0,i.kt)("p",null,"We can call functions that return Promises from inside a Promise and safely yield for their result by using the ",(0,i.kt)("inlineCode",{parentName:"p"},"await")," method of Promises. This is akin to the ",(0,i.kt)("inlineCode",{parentName:"p"},"await")," keyword in languages like JavaScript. Sometimes it might be easier to just directly resolve with a Promise though, in which case that Promise is chained onto and the outer Promise won't resolve until the inner one does."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-lua"},"local function async1()\n    return Promise.new(function(resolve, reject)\n        local ok, value = async2():await()\n        if not ok then\n            return reject(value)\n        end\n        \n        resolve(value + 1)\n    end)\nend\n")),(0,i.kt)("h2",{id:"wait-nevermind"},"Wait, nevermind."),(0,i.kt)("p",null,"Sometimes, we no longer need a value that we previously asked for (or we just want to stop a sequence of events). This could be for a variety of reasons: perhaps the user closed a menu that was loading,  or a player's ability gets interrupted, or a player skips a cutscene."),(0,i.kt)("p",null,"When situations like these come up, we can ",(0,i.kt)("em",{parentName:"p"},"cancel")," a Promise. Cancelling a Promise in its simplest form prevents the ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," or ",(0,i.kt)("inlineCode",{parentName:"p"},"catch")," handlers from running. But we can also optionally attach a hook inside of the Promise executor so we know when the Promise has been cancelled, and stop doing work."),(0,i.kt)("p",null,"There is a third parameter sent to Promise executors, in addition to ",(0,i.kt)("inlineCode",{parentName:"p"},"resolve")," and ",(0,i.kt)("inlineCode",{parentName:"p"},"reject"),", called ",(0,i.kt)("inlineCode",{parentName:"p"},"onCancel"),". ",(0,i.kt)("inlineCode",{parentName:"p"},"onCancel")," allows you to register a callback which will be called whenever the Promise is cancelled. For example:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-lua"},'local function tween(obj, tweenInfo, props)\n    return Promise.new(function(resolve, reject, onCancel)\n        local tween = TweenService:Create(obj, tweenInfo, props)\n            \n        -- Register a callback to be called if the Promise is cancelled.\n        onCancel(function()\n            tween:Cancel()\n        end) \n            \n        tween.Completed:Connect(resolve)\n        tween:Play()\n    end)\nend\n\n-- Begin tweening immediately\nlocal promise = tween(workspace.Part, TweenInfo.new(2), { Transparency = 0.5 }):andThen(function()\n    print("This is never printed.")\nend):catch(function()\n    print("This is never printed.")\nend):finally(function()\n    print("But this *is* printed!")\nend)\nwait(1)\npromise:cancel() -- Cancel the Promise, which cancels the tween.\n')),(0,i.kt)("p",null,"If we didn't register an ",(0,i.kt)("inlineCode",{parentName:"p"},"onCancel")," callback, the Promise returned from the ",(0,i.kt)("inlineCode",{parentName:"p"},"tween")," would never resolve or reject (so the ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," and ",(0,i.kt)("inlineCode",{parentName:"p"},"catch")," handlers would never get called), but the tween would still finish."),(0,i.kt)("p",null,"For times when we need to do something no matter the fate of the Promise, whether it gets resolved, rejected, ",(0,i.kt)("em",{parentName:"p"},"or")," cancelled, we can use ",(0,i.kt)("inlineCode",{parentName:"p"},"finally"),". ",(0,i.kt)("inlineCode",{parentName:"p"},"finally")," is like ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," and ",(0,i.kt)("inlineCode",{parentName:"p"},"catch"),", except it ",(0,i.kt)("em",{parentName:"p"},"always")," runs whenever the Promise is done running."),(0,i.kt)("h2",{id:"propagation"},"Propagation"),(0,i.kt)("p",null,"Cancelling a Promise will propagate upwards and cancel the entire chain of Promises. So to revisit our sequence example:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-lua"},'local promise = async1()\n    :andThen(async2)\n    :andThen(async3)\n    :andThen(async4)\n    :andThen(async5)\n    :catch(function(err)\n        warn("Oh no! This went wrong somewhere along the line:", err)\n    end)\n\npromise:cancel()\n')),(0,i.kt)("p",null,"Cancelling ",(0,i.kt)("inlineCode",{parentName:"p"},"promise")," (which is the Promise that ",(0,i.kt)("inlineCode",{parentName:"p"},"catch")," returns here) will end up cancelling every Promise in the chain, all the way up to the Promise returned by ",(0,i.kt)("inlineCode",{parentName:"p"},"async1"),". The reason this happens is because if we cancel the bottom-most Promise, we are no longer doing anything with the value, which means that no one is doing anything with the value from the Promise above it either, and so on all the way to the top. However, Promises will ",(0,i.kt)("em",{parentName:"p"},"not")," be cancelled if they have more than one ",(0,i.kt)("inlineCode",{parentName:"p"},"andThen")," handler attached to them, unless all of those are also cancelled."),(0,i.kt)("p",null,"Cancellation also propagates downwards. If a Promise is cancelled, and other Promises are dependent on that Promise, there's no way they could resolve or reject anymore, so they are cancelled as well. "),(0,i.kt)("p",null,"So, now we understand the four possible states a Promise can be in: Started (running), Resolved, Rejected, and Cancelled. It's possible to read what state a Promise is in by calling ",(0,i.kt)("inlineCode",{parentName:"p"},"promise:getStatus()"),"."),(0,i.kt)("h2",{id:"but-i-want-to-be-able-to-use-pre-existing-functions-that-yield"},"But I want to be able to use pre-existing functions that yield!"),(0,i.kt)("p",null,"You can easily turn a yielding function into a Promise-returning one by calling ",(0,i.kt)("inlineCode",{parentName:"p"},"Promise.promisify")," on it:"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-lua"},'-- Assuming myFunctionAsync is a function that yields.\nlocal myFunction = Promise.promisify(myFunctionAsync)\n\nmyFunction("some", "arguments"):andThen(print):catch(warn)\n')),(0,i.kt)("h2",{id:"problems-revisited"},"Problems, revisited"),(0,i.kt)("p",null,"Now, let's revisit the problems we laid about before and see if we've solved them by using Promises:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},"It's impossible to know if a function that you call is going to yield or not.",(0,i.kt)("ul",{parentName:"li"},(0,i.kt)("li",{parentName:"ul"},"Calling a function that returns a Promise will never yield! To use the value, we must call ",(0,i.kt)("inlineCode",{parentName:"li"},"andThen")," or ",(0,i.kt)("inlineCode",{parentName:"li"},"await"),", so we are sure that the caller knows that this is an asynchronous operation."))),(0,i.kt)("li",{parentName:"ul"},"When an asynchronous operation fails or an error is encountered, Lua functions usually either raise an error or return a success value followed by the actual value. Both of these methods lead to repeating the same patterns.",(0,i.kt)("ul",{parentName:"li"},(0,i.kt)("li",{parentName:"ul"},"We have ",(0,i.kt)("inlineCode",{parentName:"li"},"Promise:catch")," to allow catching errors that will cascade down a Promise chain and jump to the nearest ",(0,i.kt)("inlineCode",{parentName:"li"},"catch")," handler."))),(0,i.kt)("li",{parentName:"ul"},"It is difficult to deal with running multiple asynchronous operations concurrently and then retrieve all of their values at the end without extraneous machinery.",(0,i.kt)("ul",{parentName:"li"},(0,i.kt)("li",{parentName:"ul"},"We have ",(0,i.kt)("inlineCode",{parentName:"li"},"Promise.all"),", ",(0,i.kt)("inlineCode",{parentName:"li"},"Promise.race"),", or other utilities to make this a breeze."))),(0,i.kt)("li",{parentName:"ul"},"Coroutines lack easy access to introspection without manual work to enable it at the call site.",(0,i.kt)("ul",{parentName:"li"},(0,i.kt)("li",{parentName:"ul"},"We can just call ",(0,i.kt)("inlineCode",{parentName:"li"},":getStatus")," on the returned Promise!"))),(0,i.kt)("li",{parentName:"ul"},"Coroutines lack the ability to cancel an operation if the value is no longer needed without extraneous manual work at both the call site and the function implementation.",(0,i.kt)("ul",{parentName:"li"},(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("inlineCode",{parentName:"li"},"promise:cancel()")," is all we need!")))),(0,i.kt)("p",null,"Another point that's important to drive home is that you ",(0,i.kt)("em",{parentName:"p"},"can")," do all of these things without Promises, but they require duplicated work each time you do them, which makes them incompatible with each other and that allows for slight differences between implementations which can lead to usage mistakes. Centralizing and abstracting all of this logic by using Promises ensures that all of your asynchronous APIs will be consistent and composable with one another."),(0,i.kt)("h2",{id:"next-steps"},"Next steps"),(0,i.kt)("p",null,"Now that you are hopefully convinced of the benefits of using Promises in your code, move on to the ",(0,i.kt)("a",{parentName:"p",href:"/docs/Tour"},"Guide")," for a quick introduction, or dive in to the ",(0,i.kt)("a",{parentName:"p",href:"/api/Promise"},"API reference")))}d.isMDXComponent=!0}}]);